returning sec.yml

diff --git a/.github/workflows/security.yml b/.github/workflows/security.yml
--- a/.github/workflows/security.yml
+++ b/.github/workflows/security.yml
@@ -20,7 +20,7 @@ jobs:
         uses: actions/setup-python@v5
         with:
           python-version: '3.12'
-          cache: 'pip'  # Кешируем пакеты Python
+          cache: 'pip'
 
       - name: Upgrade pip and install dependencies
         run: |
@@ -30,21 +30,32 @@ jobs:
       - name: Install Trivy
         run: |
           curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
-          sudo mv trivy /usr/local/bin/
+          sudo mv ./bin/trivy /usr/local/bin/
+          trivy --version
+
+      - name: Install Gitleaks
+        run: |
+          wget --retry-connrefused --waitretry=5 --timeout=30 -t 3 -q https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -O gitleaks
+          if [ ! -f gitleaks ]; then
+            echo "Failed to download Gitleaks binary" >&2
+            exit 1
+          fi
+          chmod +x gitleaks
+          sudo mv gitleaks /usr/local/bin/gitleaks
+          gitleaks version
 
       - name: Run Bandit (SAST)
-        run: bandit -r src/
-        continue-on-error: true  # Не прерываем выполнение при ошибках
+        run: |
+          bandit -r src/ || true  # Ensure Bandit runs without failing the workflow
 
       - name: Run Pip Audit (Dependency Scan)
-        run: pip-audit
-        continue-on-error: true
+        run: |
+          pip-audit || true
 
       - name: Run Trivy on dependencies
-        run: trivy fs --scanners vuln,config .
-        continue-on-error: true
-
-      - name: Run Gitleaks (Secrets Scan) через Docker
         run: |
-          docker run --rm -v $(pwd):/src ghcr.io/gitleaks/gitleaks:v8.24.2 detect -s /src -v
-        continue-on-error: true
+          trivy fs --scanners vuln,config .
+
+      - name: Run Gitleaks (Secrets Scan)
+        run: |
+          gitleaks detect -v || true
